runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START env_variables]
env_variables:
  MEMCACHE_SERVER: your-memcache-server
  # If you are using a third-party or self-hosted Memcached server with SASL
  # authentiation enabled, uncomment and fill in these values with your
  # username and password.
  # MEMCACHE_USERNAME: your-memcache-username
  # MEMCACHE_PASSWORD: your-memcache-password
# [END env_variables]
