sudo: false
language: python
services:
- memcached
- mysql
- redis-server
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
    secure: fsBH64/WqTe7lRcn4awZU7q6+euS/LHgMq2Ee2ubaoxUei2GbK5jBgnGHxOKVL5sZ4KNfTc7d6NR5BB1ZouYr2v4q1ip7Il9kFG4g5qV4cIXzHusXkrjvIzQLupNpcD9JJZr1fmYh4AqXRs2kP/nZqb7xB6Jm/O+h+aeC1bhhBg=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - portaudio19-dev
    - python3.6
    - python3.6-dev
install:
- pip install --upgrade pip wheel virtualenv
- pip install --upgrade nox-automation
- pip install --upgrade git+https://github.com/dhermes/ci-diff-helper.git
script:
- "./scripts/travis.sh"
