service: tictactoe
runtime: python27
version: 1
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: chatactoe.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
