#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/python" ]; then
  "$basedir/python"  "$basedir/node_modules/korean-sentiment-analyzer/morphemeServer.py" "$@"
  ret=$?
else 
  python  "$basedir/node_modules/korean-sentiment-analyzer/morphemeServer.py" "$@"
  ret=$?
fi
exit $ret
